### ISSUE TITLE
Renewals page creation

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#363]
1. always ask someone to enter their e-mail before entering into the page
2. say that people can unify / change their e-mail by contacting us
3. always write to the original e-mail to tell people that their leaves are up for renewal and to confirm that they have been renewed 
4. give people the option on renewal to be on the donor list or not - default is yes - also get people to review the current terms and conditions and confirm they they are renewing their own original sponsored leaves - terms should add something about confirming that you're only renewing your own leaves - add date of last update to the terms and conditions.

This page should also include an option for 'recover expired sponsorships'

**Comment by jrosindell** [comment]
Page design.

Should be a list of all leaves by the user with that e-mail
Should be a tick box for each one that needs renewal
Should work like sponsor leaf page with 'accept terms and donate now' button.

**Comment by jrosindell** [comment]
James and Yan to draw a mockup with labelled actions on it then hope to outsource if feasible

**Comment by lentinj** [comment]
Notes from meeting:

* There should be a page that can trigger the renewal e-mail send manually (in lieu of a full login, which is getting carried away)
* Use JWT as part of e-mail link (i.e. a base64'ed dictionary that's signed by us), containing sponsor's e-mail address and a link expiry time. Valid e-mail addresses can't be harvested since only we can generate the links. Try and avoid having a bunch of state in the database for this.
* Renewals page should be as "one-click" as possible, ideally the default being to renew all existing items (generally one anyway, but possibly up to ~50). Maybe instead of checking everything to renew, uncheck, or a bin/save for later. The page should resemble a shopping cart process.

**Comment by lentinj** [comment]
This is starting to come together, and displaying the various categories of sponsorships. Still a bit too messy to commit, but it's here if you're curious: https://github.com/lentinj/OZtree/tree/wip-363

I've created a ``test/fixtures/reservations.sql`` that will move existing entries aside, and populate with a bunch of made-up sponsorships in different states. As well as being useful for developing / testing, the fixture sponsors will probably be useful for inspecting the end-result in various modes and edge cases.

**Comment by hyanwong** [comment]
Great, thanks for setting up the test fixture(s) - should be really useful. Don't hesitate to reorganise anything in the `tests/` dir, as I didn't really know what I was doing when setting it up.

**Comment by jrosindell** [comment]
I've just thought of an edge case - which is that some leaves will have price = NULL and yet are sponsored e.g. the panda.

Maybe in such cases we should take the price paid before as the renewal.

**Comment by hyanwong** [comment]
I think these are in the "banned" list (a separate table), so we could give those leaves a price (the price paid) and I think they will still be listed as }"contact us" in the sponsorship box

**Comment by lentinj** [comment]
Okay, presumably we should also show a hint at the bottom, before the donate button. having 1 "banned" item out of ~50 sponsorships won't be particularly obvious if you're trying to renew the lot.

**Comment by hyanwong** [comment]
There's only one (out of ~20) species that are "banned" that have been sponsored so far. So we shouldn't put too much effort into making this aspect look perfect.

**Comment by lentinj** [comment]
This is starting to come together. The fixture SQL generates some standard users for playing, so you don't have to recreate conditions, have a go with:

* ``/sponsor_renew.html/fixture_single@example.com``
* ``/sponsor_renew.html/fixture_agemixture@example.com``
* ``/sponsor_renew.html/fixture_bannedott@example.com``

Some TODOs and questions:

* No Token-parsing yet, it's just a raw e-mail address.
* The form doesn't actually do anything, but probably worth looking at the paypal end first.
* What to display when your previous donation didn't include gift aid. Either we include gift aid declaration at this point, ask to e-mail if they want to add it, or just say nothing.

**Comment by hyanwong** [comment]
So how does the fixture stuff work, if you have an existing reservations table (as I do on my local version)? If I checkout the 3.5 branch and go to `127.0.0.1:8000/sponsor_renew.html/fixture_single@example.com` I get

> <class 'AttributeError'> 'NoneType' object has no attribute 'fetchone'
> 
> Version
> web2py™	Version 2.21.1-stable+timestamp.2020.11.27.18.21.43
> Python	Python 3.9.4: /Users/yan/opt/miniconda3/bin/python3 (prefix: /Users/yan/opt/miniconda3)
> Traceback (most recent call last):
>   File "/Users/yan/Documents/Research/OneZoom/web2py/gluon/restricted.py", line 219, in restricted
>     exec(ccode, environment)
>   File "/Users/yan/Documents/Research/OneZoom/web2py/applications/OZtree/controllers/default.py", line 1968, in <module>
>   File "/Users/yan/Documents/Research/OneZoom/web2py/gluon/globals.py", line 430, in <lambda>
>     self._caller = lambda f: f()
>   File "/Users/yan/Documents/Research/OneZoom/web2py/applications/OZtree/controllers/default.py", line 837, in sponsor_renew
>     for r in db(db.reservations.e_mail == user_email).iterselect(
>   File "/Users/yan/Documents/Research/OneZoom/web2py/gluon/packages/dal/pydal/objects.py", line 3563, in __iter__
>     row = next(self)
>   File "/Users/yan/Documents/Research/OneZoom/web2py/gluon/packages/dal/pydal/objects.py", line 3535, in __next__
>     db_row = self.cursor.fetchone()

But it may be that I have a too-old version of `pymysql` or something

**Comment by lentinj** [comment]
> So how does the fixture stuff work

It's not fancy, it's just a SQL script to run that moves the table content to one side and populates with known values: https://github.com/OneZoom/OZtree/blob/3.5/tests/fixtures/reservations.sql

Possibly upgrading ``pymysql`` would help, or could try replacing ``iterselect()`` with ``select()``, looks like the former is exercising codepaths the MySQL driver can't use.

**Comment by hyanwong** [comment]
> > So how does the fixture stuff work
> 
> It's not fancy, it's just a SQL script to run that moves the table content to one side and populates with known values: https://github.com/OneZoom/OZtree/blob/3.5/tests/fixtures/reservations.sql

Right, but when does it actually run? Is it triggered by something specific in the test suite? I'm assuming visiting a url outside of the test suite won't work (as the correct info isn't in the DB)

> Possibly upgrading `pymysql` would help, or could try replacing `iterselect()` with `select()`, looks like the former is exercising codepaths the MySQL driver can't use.

I seem to have v 1.0.2 of `pymysql` installed, which is, I think, the latest. So I presume it's not that. And I seem to be running the latest web2py (and mysql 8.0). So I'm not sure what the issue is.

**Comment by lentinj** [comment]
> Right, but when does it actually run? Is it triggered by something specific in the test suite? I'm assuming visiting a url outside of the test suite won't work (as the correct info isn't in the DB)

The idea is that you can run it yourself with your preferred mysql client for visual checks outside a test suite, or a test suite would execute it as part of ``setUpClass()``.

> So I'm not sure what the issue is.

Did replacing ``iterselect()`` make the issue go away?

**Comment by hyanwong** [comment]
> Possibly upgrading `pymysql` would help, or could try replacing `iterselect()` with `select()`, looks like the former is exercising codepaths the MySQL driver can't use.

If I use "select" instead, I get:

> Traceback (most recent call last):
>  File "/Users/yan/Documents/Research/OneZoom/web2py/gluon/restricted.py", line 219, in restricted
>    exec(ccode, environment)
>  File "/Users/yan/Documents/Research/OneZoom/web2py/applications/OZtree/views/default/sponsor_renew.html", line 209, in <module>

I assume this is an issue with looking for a non-existent email in the DB (since I didn't run the fixture code first).
AttributeError: 'NoneType' object has no attribute 'e_mail'

**Comment by lentinj** [comment]
Yup, non-existent e-mail. The above stops using iterselect and patches things to the point an empty page can render, although presumably we should have a more obvious "You haven't sponsored anything, here's how" message in this case.

**Comment by hyanwong** [comment]
I think `iterselect()` rather than `select()` is fine as long as the edge case of no returned items is covered.

**Comment by jrosindell** [comment]
A few comments after reviewing the page as it stands now....

- on http://127.0.0.1:8000/sponsor_renew.html/fixture_agemixture@example.com next to Magpie goose says 'Renew by donating £150' but this one is not available to sponsor
- If people add to their donation amount - how will this be posted.  We use the reservations table for accounting too so it should be that any extra they donate is added somehow to the totals of all the leaves in the basket.  Maybe it's easiest to add all the extra onto one of the leaves because if we divide it up we may run into issues with things not adding up at the level of pennies.
- should 'donor page' open as a new tab? 
- should we have a link to each leaf on the tree that opens as a new tab?  I think yes we should.
- '£0 or greater' - the 0 needs to be updated. Also, if I select and then deselect leaves the total does not update
- 'There is also a public page available at TODO: that you can share if you wish.' @hyanwong do we want this public page to show the same species as have 'show on donor page' selected? Probably we do?
- For the 'select all that are due for renewal and proceed' button I'd suggest the pill button used elsewhere on the site.  For the 'donate' button I'd agree that we should use a PayPal one - but also OK as it is.  If we use PayPal then we should update it on the main sponsorship page as well

**Comment by jrosindell** [comment]
For the message about not gift-aiding.  I'd suggest....

We do not have a gift aid declaration from you. If you are a UK tax payer please consider making a Gift Aid declaration which will increase the value of your donation by 25% at no cost to you. If you sponsor any new leaf you will be able to make a gift aid declaration as part of that process and this declaration would also apply to any donation you make here to renew existing leaves. Alternatively, if you want to make a new gift aid declaration without sponsoring any new leaves please write to us.

**Comment by lentinj** [comment]
> If people add to their donation amount - how will this be posted.

The other option would be to record the extra donation separately, which could be useful if you then accept donations without sposorship, but probably isn't worth the faff. I was assuming it would be divided amongst the sponsored items arbitrarily, as you say.

**Comment by lentinj** [comment]
I've changed the behavior (or will once it's pushed) of the donation amount box, before it was making sure that the amount was at least the required amount, now if I deselect a renewal, the amount will go down too. I think this is more intuitive, but thoughts welcome.

We could try and work out if there was an extra amount added on deselect and preserve it, but I don't think it's worth it. If we still think this is confusing, I think we separate the price out into (x) for leaves + (y) extra donation.

**Comment by jrosindell** [comment]
What about a separate box or radio button to add 5,10,20, some other amount to your sponsorship? 
To keep things simple I think the extra could be added to whichever is first (according to some ordering) to save the hassle of another table / system to record extra donations.

**Comment by lentinj** [comment]
Okay, lets keep it separate in the UI.

In the DB if it's added to whichever is first that makes it easier to reconstitute the extra donation too.

**Comment by jrosindell** [comment]
Yes I think that's best - because which donation the extra is added to doesn't really matter as long as it sums to the correct amount

**Comment by lentinj** [comment]
I think all your comments from before are now sorted.

> should we have a link to each leaf on the tree that opens as a new tab? I think yes we should.

We already did (on the image), but I've added "leafout" styling from the homepage, which is what it should have had. Or do you mean the text also?

> For the 'donate' button...

I've turned this into a pill for now too, to make it work I've moved the terms/conditions link to a paragraph above. Seem reasonable? I think this looks better than the paypal ![](https://www.paypalobjects.com/en_GB/i/btn/btn_donate_LG.gif)

**Comment by jrosindell** [comment]
I think the pill choice and leaflet styling sound like the ideal solutions here.

**Comment by lentinj** [comment]
Note the above commit restructures how the reservations fixture is formed, they're now ``agemixture@fixture.example.com`` in line with unit tests.

**Comment by hyanwong** [comment]
I've just been trying the unit tests in `applications/OZtree/tests/unit/test_modules_sponsorship.py` and I forgot that a new installation won't have prices set on any of the leaves, so perhaps it's worth having a test that checks for at least one non-null price in `ordered_leaves` and if not, reports an error that says "You need to set prices first by going to `http://127.0.0.1:8000/manage/SET_PRICES`" (or whatever the URL is for the local server)

**Comment by hyanwong** [comment]
@lentinj - I think it would be helpful to add a README.md file to `./tests/` which gives brief instructions for how to run the tests (and maybe a (very short) explanation for how they work - e.g. "tests in `unit/test_modules_sponsorship.py` add a few rows to the existing reservations table, and delete them at the end of the tests". What do you think?

**Comment by jrosindell** [comment]
For user_donor_show = NULL the behaviour should be different to 0.  0 means the user has already before been given the option to show and decided not to whereas NULL means they have never been asked.  If it's NULL then the user_donor_show should be ticked by default.  Yan and I think this is OK because basically the whole thing is about sponsorship which means making public your donation.

**Comment by hyanwong** [comment]
If I try to look at a renewals page with 

```
[sponsorship]
allow_sponsorship = manager
```

in my appconfig.ini file, I get the following error message:

<img width="920" alt="Screenshot 2021-06-06 at 22 11 37" src="https://user-images.githubusercontent.com/4699014/120940238-2f31d380-c714-11eb-93d7-56deeea193f6.png">

What should happen is that `allow_sponsorship` should be able to be set to 0, 1, or a group name. If a group name, then if the user is logged in and the user belongs to the group specified, then it acts as a 0, otherwise it acts as a 0. This allows us to test on beta.onezoom.org, where we set `allow_sponsorship = manager` so that we can test all the sponsoring framework, but a causal visitor who accidentally ends up on the beta site cannot see anything to do with sponsorship.

**Comment by lentinj** [comment]
> I think it would be helpful to add a README.md

Yes, I was going to bring up this as part of the testing ticket, and explain the fixtures as well. We could also do with a test runner wrapping this and any others in future, probably an extra task in the Gruntfile since that's what's already there.

**Comment by lentinj** [comment]
> Another (very minor) issue is that I think the text that currently says "Now sponsored by Fixture Single", but I think it should say "Sorry, this leaf has now been sponsored by someone else".

@jrosindell I think the wording came from your mockups, any comments? Changing it simplifies the code, since it doesn't need to dig out the current sponsor any more.

**Comment by lentinj** [comment]
> When visiting the sponsor_renew.html page, and locating an item where user_donor_show = NULL, currently the page treats this as equivalent to 0, and unticks the "show on donor page" checkbox. However we want it to be equivalent to 1 instead.

The web2py DAL seems to be doing this for us, boolean fields seem to assume NULL == False, so it's not as simple as adding another check in the view. Worth digging deeper to sort out?

**Comment by hyanwong** [comment]
We could shift the field name to `user_donor_hide`, and negate all the existing 0/1 values?

**Comment by lentinj** [comment]
I'm assuming there's a "don't do that" option in the DAL that's going to be quicker to find than recreating the field. But yes, ``user_donor_hide`` is probably the more natural way around.

**Comment by hyanwong** [comment]
We're going to be fiddling with (a copy of) the main reservations table to get it into the correct format anyway, so I think a small change from 0<->1 plus a rename would be OK, if it makes the whole thing more sane.

**Comment by lentinj** [comment]
Amassing remaining TODOs:

- [ ] Renew via. Token
- [ ] Document testing / test runner
- [ ] ``user_donor_hide``
- [ ] "Now sponsored by Fixture Single" vs. "Sorry, this leaf has now been sponsored by someone else".

**Comment by lentinj** [comment]
For the token-renewal, web2py has [signed URLs](http://web2py.com/books/default/chapter/29/04/the-core#Digitally-signed-urls), which is pretty much what we're after. There's no built-in concept of link expiry though, should we add one and if so how long should they last?

**Comment by hyanwong** [comment]
Why would we want the link to expire? I think the donor would expect this to be a permanent link, wouldn't they?

**Comment by hyanwong** [comment]
(but this wouldn't apply to the "public" donor page, would it? I think we decided that for that, we would create a permanent link out of the `reservations.username` field. I can't recall how we get people to populate that field, though (or if we do so automatically from the `verified_donor_name` somehow. Do you remember @jrosindell ?

**Comment by hyanwong** [comment]
> For the token-renewal, web2py has [signed URLs](http://web2py.com/books/default/chapter/29/04/the-core#Digitally-signed-urls), which is pretty much what we're after. There's no built-in concept of link expiry though, should we add one and if so how long should they last?

I think that @jrosindell opened a specific issue about tokens at https://github.com/OneZoom/OZtree/issues/394, so maybe this is a good discussion to move there? 

Re the public page, I've just opened a discussion of usernames at #394

**Comment by lentinj** [comment]
For ``user_donor_hide``, what would [the sponsor form text](https://github.com/OneZoom/OZtree/blob/main/views/default/sponsor_leaf.load#L111) get replaced with?

**Comment by hyanwong** [comment]
Do you mean what should we change it to in `sponsor_leaf` now that they will also get a "donor" page, or what should the (mouseover?) text be in the sponsor_renew page?

**Comment by hyanwong** [comment]
If the former, perhaps something like this:

```
{{=XML(T('We would love to be able to thank you by name:  if this box is ticked we’ll add your name to our public %s and create a page for your sponsorships that you can show to others, if you wish.') % (A(T('list of donors'), _href='/donor_list', _target="blank"),))}}
```

**Comment by lentinj** [comment]
I mean if ``user_donor_show`` becomes ``user_donor_hide``, and the linked checkbox's action inverts, what would the label become?

**Comment by jrosindell** [comment]
I'd suggest this....

Your sponsorship is a public acknowledgement of your donation.  We now acknowledge donors on the tree and on our public list of donors and you can create a page for your sponsorships that you can show to others, if you wish. Tick this box if you would prefer your sponsorship to be only acknowledged on the tree.

**Comment by lentinj** [comment]
@hyanwong https://github.com/OneZoom/OZtree/commit/5d158910e6755e8dd12430c18b8a70b833c78870 switches to ``user_donor_hide``, but there's nothing to do the migration itself, presumably you'll add it to your list somewhere?

**Comment by hyanwong** [comment]
Yep, we'll need to make a list of everything that needs to be done for the one-off migration

**Comment by jrosindell** [comment]
Behaviour of the 'donor_username' field - should be copied to all reservations with the same e-mail but not to any with another e-mail. We need to discuss this later - how it interacts with the renewals and initial donation page, how it interacts with the donor show and the interpretation around setting the name in the first place. it is auto set, or blank and they type it in. Probably it should their name with a number if necessary to make it unique.

**Comment by jrosindell** [comment]
As discussed in #304 I've so far had problems accessing this page in the deployment.
