### ISSUE TITLE
Web2py causing issues with grunt test-server

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#589]
We get a series of errors when trying to  grunt test-server - documented with comments from @lentinj below.  Recorded here for considering in some future sprint...

There should be enough of a MySQL database for the website to run, we don't currently have a separate test database. Instead, it's careful about not assuming anything exists and tidying up after itself.

This seems to suggest it's the local MySQL using a character set that Web2Py's copy of pymysql can't handle, which seems a reasonable conclusion looking at the stack trace:

https://stackoverflow.com/questions/45368336/error-keyerror-255-when-executing-pymysql-connect

The bodge in the above link might be interesting, but isn't really a long-term answer. The version of pymysql bundled in web2py is getting old and hasn't been updated, which isn't encouraging at all:

https://github.com/web2py/web2py/issues/2056

However I'd expect this to be a problem when launching web2py locally too (and it isn't)

```
> grunt test-server
Running "exec:test_server" (exec) task
test_getOTT (__main__.TestControllersAPI)
Can fetch OTT names in variety of forms ...
ERROR
ERROR
test_search_init (__main__.TestControllersAPI)
Search for arbitary node/name combinations ...
ERROR
ERROR
======================================================================
ERROR: test_getOTT (__main__.TestControllersAPI)
Can fetch OTT names in variety of forms
----------------------------------------------------------------------
Traceback (most recent call last):
File "applications/OZtree/tests/unit/test_controllers_API.py",
line 71, in test_getOTT
self.assertEqual(getOTT(eol=-1), {'eol': {}, 'errors': []})
File "applications/OZtree/tests/unit/test_controllers_API.py",
line 21, in fn
return endpoint()
File
"/Users/jrosinde/Documents/OneZoom/web2py/applications/OZtree/controllers/API.py",
line 573, in getOTT
leaf_rows =
db(db.ordered_leaves[s].belongs(id_list)).select(db.ordered_leaves[s],
db.ordered_leaves.ott)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/objects.py",
line 2720, in select
return adapter.select(self.query, fields, attributes)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 908, in select
return self._select_aux(sql, fields, attributes, colnames)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 865, in select_aux
rows = self._select_aux_execute(sql)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 859, in _select_aux_execute
self.execute(sql)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/__init_.py",
line 65, in wrap
if not args[0].connection:
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 32, in connection
return self.get_connection()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 65, in get_connection
connection = self.connector()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/mysql.py",
line 64, in connector
conn = self.driver.connect(**self.driver_args)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/__init__.py",
line 90, in Connect
return Connection(*args, **kwargs)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 688, in _init__
self.connect()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 905, in connect
self._get_server_information()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 1231, in _get_server_information
self.server_charset = charset_by_id(lang).name
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/charset.py",
line 38, in by_id
return self._by_id[id]
KeyError: 255
======================================================================
ERROR: test_getOTT (__main_.TestControllersAPI)
Can fetch OTT names in variety of forms
----------------------------------------------------------------------
Traceback (most recent call last):
File "applications/OZtree/tests/unit/test_controllers_API.py",
line 36, in tearDown
db.rollback()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/base.py",
line 825, in rollback
self._adapter.rollback()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/__init__.py",
line 56, in wrap
if args[0].connection:
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 32, in connection
return self.get_connection()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 65, in get_connection
connection = self.connector()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/mysql.py",
line 64, in connector
conn = self.driver.connect(**self.driver_args)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/__init__.py",
line 90, in Connect
return Connection(*args, **kwargs)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 688, in _init__
self.connect()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 905, in connect
self._get_server_information()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 1231, in _get_server_information
self.server_charset = charset_by_id(lang).name
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/charset.py",
line 38, in by_id
return self._by_id[id]
KeyError: 255
======================================================================
ERROR: test_search_init (__main_.TestControllersAPI)
Search for arbitary node/name combinations
----------------------------------------------------------------------
Traceback (most recent call last):
File "applications/OZtree/tests/unit/test_controllers_API.py",
line 43, in test_search_init
leaf = db((db.ordered_leaves.ott != None) &
(db.ordered_leaves.name != None)).select(orderby='ott',
limitby=(0,1))[0]
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/objects.py",
line 2720, in select
return adapter.select(self.query, fields, attributes)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 908, in select
return self._select_aux(sql, fields, attributes, colnames)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 865, in select_aux
rows = self._select_aux_execute(sql)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/base.py",
line 859, in _select_aux_execute
self.execute(sql)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/__init_.py",
line 65, in wrap
if not args[0].connection:
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 32, in connection
return self.get_connection()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 65, in get_connection
connection = self.connector()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/mysql.py",
line 64, in connector
conn = self.driver.connect(**self.driver_args)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/__init__.py",
line 90, in Connect
return Connection(*args, **kwargs)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 688, in _init__
self.connect()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 905, in connect
self._get_server_information()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 1231, in _get_server_information
self.server_charset = charset_by_id(lang).name
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/charset.py",
line 38, in by_id
return self._by_id[id]
KeyError: 255
======================================================================
ERROR: test_search_init (__main_.TestControllersAPI)
Search for arbitary node/name combinations
----------------------------------------------------------------------
Traceback (most recent call last):
File "applications/OZtree/tests/unit/test_controllers_API.py",
line 36, in tearDown
db.rollback()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/base.py",
line 825, in rollback
self._adapter.rollback()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/__init__.py",
line 56, in wrap
if args[0].connection:
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 32, in connection
return self.get_connection()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/connection.py",
line 65, in get_connection
connection = self.connector()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/packages/dal/pydal/adapters/mysql.py",
line 64, in connector
conn = self.driver.connect(**self.dri
ver_args)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/__init__.py",
line 90, in Connect
return Connection(*args, **kwargs)
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 688, in __init__
self.connect()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 905, in connect
self._get_server_information()
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/connections.py",
line 1231, in _get_server_information
self.server_charset = charset_by_id(lang).name
File
"/Users/jrosinde/Documents/OneZoom/web2py/gluon/contrib/pymysql/charset.py",
line 38, in by_id
return self._by_id[id]
KeyError: 255
----------------------------------------------------------------------
Ran 2 tests in 0.011s
FAILED (errors=4)
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2022
Version 2.22.3-stable+timestamp.2022.02.15.15.14.38
Database drivers available: sqlite3, imaplib, pymysql
Traceback (most recent call last):
File "/Users/jrosinde/Documents/OneZoom/web2py/gluon/shell.py", line
306, in run
execfile(startfile, _env)
File "/Users/jrosinde/Documents/OneZoom/web2py/gluon/shell.py", line
41, in execfile
exec(code, global_vars, local_vars)
File "applications/OZtree/tests/unit/test_controllers_API.py", line
117, in <module>
sys.exit(1)
SystemExit: 1
Exited with code: 1.
Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:test_server" failed. Use --force to continue.
Aborted due to warnings.
```

**Comment by lentinj** [comment]
FWIW the corresponding lines mentioned in the link are here: https://github.com/web2py/web2py/blob/master/gluon/contrib/pymysql/connections.py#L1231 - you'd need to modify your web2py checkout.

However, I don't think this is worth trying. Not only is it a bad idea in general to go poking around in the web2py source, if the site does work then it's more subtle than a version incompatibility. Maybe grunt is setting environment variables causing MySQL to choose a different, incompatible locale?

It'd be good to know what [MySQL version](https://stackoverflow.com/questions/8987679/how-to-retrieve-the-current-version-of-a-mysql-database-management-system-dbms) and Python version (the header after running ``python``) you're using.

It'd also be useful to to try without grunt, i.e. run one of the tests with, for example:-

```
python3 web2py.py -S OZtree -M -R applications/OZtree/tests/unit/test_modules_sponsorship.py
```

**Comment by jrosindell** [comment]
SQL version 8.0.29
Python version 3.7.13 (noted that grunt file hard codes 3.7)
Trying without grunt fails in the same way as it did before.
I guess this doesn't require any follow up action given what you've said above but I'm recording the info here for future reference.

**Comment by hyanwong** [comment]
What's the web2py version?

**Comment by hyanwong** [comment]
FWIW `python3 web2py.py -S OZtree -M -R applications/OZtree/tests/unit/test_modules_sponsorship.py` works for me, MySQL 8.0.20, Python 3.9.1, web2py 2.22.3-stable+timestamp.2022.02.15.15.14.38.

But I do get some test failures:

```
======================================================================
ERROR: test_reservation_total_counts (__main__.TestSponsorship)
Can count for the home page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "applications/OZtree/tests/unit/test_modules_sponsorship.py", line 180, in test_reservation_total_counts
    reservations_renewed = util.purchase_reservation(
  File "/Users/yan/Documents/Research/OneZoom/web2py/applications/OZtree/tests/unit/util.py", line 155, in purchase_reservation
    raise ValueError("OTT %d wasn't available: %s" % (ott, status))
ValueError: OTT 4787763 wasn't available: sponsored

======================================================================
ERROR: test_reservation_total_counts (__main__.TestSponsorRenewRequestLogic)
Can count for the home page
----------------------------------------------------------------------
Traceback (most recent call last):
  File "applications/OZtree/tests/unit/test_modules_sponsorship.py", line 180, in test_reservation_total_counts
    reservations_renewed = util.purchase_reservation(
  File "/Users/yan/Documents/Research/OneZoom/web2py/applications/OZtree/tests/unit/util.py", line 155, in purchase_reservation
    raise ValueError("OTT %d wasn't available: %s" % (ott, status))
ValueError: OTT 4787763 wasn't available: sponsored

----------------------------------------------------------------------
Ran 39 tests in 2.639s

FAILED (errors=2)
```

I guess if I unsponsor OTT 4787763 then this might work, but I'm suprised that it simply doesn't pick a known unsponsored OTT for testing.

**Comment by lentinj** [comment]
> I guess if I unsponsor OTT 4787763 then this might work, but I'm suprised that it simply doesn't pick a known unsponsored OTT for testing.

It's trying to purchase an OTT that should have expired, by being too old. So the fact that it's still sponsored is part of the test:

https://github.com/OneZoom/OZtree/blob/4a2c8d393bbfcb5663819fd0010079e65666e72c/tests/unit/test_modules_sponsorship.py#L172-L182

**Comment by hyanwong** [comment]
When @jrosindell says "main site" he doesn't mean an OneZoom.org, but on his local installation. dropping the encoding from the DB string is a temporary workaround. It would be nice to fix it properly.
